src/gz istoreos_core https://mirrors.cernet.edu.cn/openwrt/releases/24.10.5/targets/x86/64/packages
src/gz istoreos_base https://mirrors.cernet.edu.cn/openwrt/releases/24.10.5/packages/x86_64/base
src/gz istoreos_kmods https://mirrors.cernet.edu.cn/openwrt/releases/24.10.5/targets/x86/64/kmods/6.6.119-1-484466e2719a743506c36b4bb2103582
src/gz istoreos_luci https://mirrors.cernet.edu.cn/openwrt/releases/24.10.5/packages/x86_64/luci
src/gz istoreos_packages https://mirrors.cernet.edu.cn/openwrt/releases/24.10.5/packages/x86_64/packages
src/gz istoreos_routing https://mirrors.cernet.edu.cn/openwrt/releases/24.10.5/packages/x86_64/routing
src/gz istoreos_telephony https://mirrors.cernet.edu.cn/openwrt/releases/24.10.5/packages/x86_64/telephony